Greatly improved the favicons upgrade script

diff --git a/favicons/upgrade b/favicons/upgrade
--- a/favicons/upgrade
+++ b/favicons/upgrade
@@ -1,55 +1,69 @@
 #!/bin/bash
 
+# SYNOPSIS
+#
+#	|<DOMAIN>|
+#	|...|
+#	[PROVIDER={duckduckgo|google}] ./upgrade
+#
+# EXAMPLE
+#
+#	find -type f -iname '*.webp' \
+#		| sed 's|.*/||; s|.webp$||;' \
+#		| ./upgrade
+
 set -Eeuo pipefail
+
+declare -ri MAX_WIDTH=16
+declare -ri MAX_HEIGHT=16
+
+function find_best_index() {
+	local -a data=()
+	while IFS=$'\t' read -r index width height _; do
+		if [[ "$width" -eq "$MAX_WIDTH" && "$height" -eq "$MAX_HEIGHT" ]]; then
+			printf '%d\n' "$index"
+			return
+		fi
+		data+=("$((width * height))"$'\t'"$index")
+	done < <(identify -format $'%p\t%w\t%h\n' "${1?no input file}")
+	if [[ ${#data[@]} -eq 0 ]]; then
+		echo "$0: error: no indexes found in $1" >&2
+		exit 1
+	fi
+	printf '%s\n' "${data[@]}" \
+		| sort -nr \
+		| cut -f2 \
+		| head -1
+}
 
 declare -r PROVIDER="${PROVIDER:-google}"
 
-declare -i EXIT_CODE=0
-
-case "$PROVIDER" in
-'duckduckgo'|'ddg')
-	download_favicon() {
-		local -r DOMAIN="${1?no domain}"
-		local -r FAVICON_FILE="${2?no favicon file}"
-		curl --location --silent -- "https://external-content.duckduckgo.com/ip3/$DOMAIN.ico" \
-			> "$FAVICON_FILE"
-	}
-	;;
-'google')
-	download_favicon() {
-		local -r DOMAIN="${1?no domain}"
-		local -r FAVICON_FILE="${2?no favicon file}"
-		curl --location --silent -- "https://www.google.com/s2/favicons?domain=$DOMAIN&sz=16" \
-			> "$FAVICON_FILE"
-	}
-	;;
-*)
-	echo "$0: fatal: unrecognized favicon provider: $PROVIDER" >&2
-	exit 1
-	;;
-esac
-
 echo "$0: info: favicon provider: $PROVIDER" >&2
 
-while read -r DOMAIN; do
-	printf '%s\n' "$DOMAIN"
-	TMP_FAVICON_FILE="$DOMAIN~"
-	download_favicon "$DOMAIN" "$TMP_FAVICON_FILE"
-	MIME_TYPE="$(file --brief --mime-type "$TMP_FAVICON_FILE")"
-	case "$MIME_TYPE" in
-	'image/jpeg')
-		echo "$0: warn: $DOMAIN provided a JPEG favicon" >&2
-		cwebp -quiet -lossless -z 9 -resize 16 16 "$TMP_FAVICON_FILE" -o "$DOMAIN.webp"
-		;;
-	'image/png'|'image/webp')
-		cwebp -quiet -lossless -z 9 -resize 16 16 "$TMP_FAVICON_FILE" -o "$DOMAIN.webp"
-		;;
-	*)
-		echo "$0: error: unrecognized MIME-type $MIME_TYPE for $TMP_FAVICON_FILE" >&2
-		EXIT_CODE=1
-		;;
+while read -r domain; do
+	printf '%s\n' "$domain"
+	tmp_favicon_file="$domain~"
+	favicon_url=
+	case "$PROVIDER" in
+	'duckduckgo') favicon_url="https://external-content.duckduckgo.com/ip3/$domain.ico";;
+	'google') favicon_url="https://www.google.com/s2/favicons?domain=$domain&sz=16";;
+	*) echo "$0: fatal: unrecognized favicon provider: $PROVIDER" >&2; exit 1;;
 	esac
-	rm -f -- "$TMP_FAVICON_FILE"
+	curl --silent --location --output "$tmp_favicon_file" "$favicon_url"
+	mime_type="$(file --brief --mime-type -- "$tmp_favicon_file")"
+	case "$mime_type" in
+	'image/avif') prefix=avif; index=0;;
+	'image/jpeg') prefix=jpeg; index=0;;
+	'image/png') prefix=png; index=0;;
+	'image/svg+xml') prefix=svg; index=0;;
+	'image/vnd.microsoft.icon') prefix=ico; index="$(find_best_index "$prefix:$tmp_favicon_file")";;
+	'image/webp') prefix=webp; index="$(find_best_index "$prefix:$tmp_favicon_file")";;
+	'inode/x-empty') echo "$0: warn: empty for $domain" >&2; prefix=;;
+	*) echo "$0: fatal: unrecognized MIME type: $mime_type for $domain" >&2; exit 1;;
+	esac
+	if [[ -n "$prefix" ]]; then
+		convert "$prefix:$tmp_favicon_file[$index]" -resize "${MAX_WIDTH}x$MAX_HEIGHT>" png:"$tmp_favicon_file"
+		cwebp -quiet -lossless -z 9 "$tmp_favicon_file" -o "$domain.webp"
+	fi
+	rm --force -- "$tmp_favicon_file"
 done
-
-exit $EXIT_CODE
